const express = require('express');
const cors = require('cors');
const mongoose = require('mongoose');
const XLSX = require('xlsx');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 4000;

// ── Excel export temp directory ───────────────────────────────────────────────────────────────
const EXPORT_DIR = path.join(__dirname, 'excel_exports');
if (!fs.existsSync(EXPORT_DIR)) fs.mkdirSync(EXPORT_DIR, { recursive: true });

// Serve exported Excel files as static assets (accessible by URL)
// e.g. http://your-server:4000/exports/abc123.xlsx
app.use('/exports', express.static(EXPORT_DIR));

app.use(cors());
app.use(express.json({ limit: '2mb' }));

const chatSessionSchema = new mongoose.Schema(
  {
    actor_id: { type: String, required: true, index: true },
    session_id: { type: String, required: true, index: true },
    title: { type: String, default: 'New Chat' },
    backendType: { type: String, default: 'AWS' },
    messages: { type: Array, default: [] },
    updated_at: { type: Date, default: Date.now }
  },
  { timestamps: true }
);
chatSessionSchema.index({ actor_id: 1, session_id: 1 }, { unique: true });

const feedbackSchema = new mongoose.Schema(
  {
    actor_id: { type: String, required: true },
    session_id: { type: String, required: true },
    message_index: { type: Number, required: true },
    type: { type: String, enum: ['like', 'dislike', 'suggest'], required: true },
    reasons: { type: [String], default: [] },
    comment: { type: String, default: '' }
  },
  { timestamps: true }
);

const ChatSession = mongoose.model('ChatSession', chatSessionSchema);
const Feedback = mongoose.model('Feedback', feedbackSchema);

app.get('/health', (_req, res) => res.json({ ok: true }));

// ───────────────────────────────────────────────────────────────────────────
// POST /api/export-excel
// Called by the WhatsApp bot when user replies "all" to get full data.
//
// Request body:
//   { data: Array<Object>, filename?: string, query?: string }
//
// Response:
//   { url: "http://your-server:4000/exports/abc123.xlsx",
//     filename: "CGMSCL_Export_abc123.xlsx",
//     expires_in: "30 minutes" }
// ───────────────────────────────────────────────────────────────────────────
app.post('/api/export-excel', (req, res) => {
  try {
    const { data, filename, query } = req.body || {};

    if (!data || !Array.isArray(data) || data.length === 0) {
      return res.status(400).json({ error: 'data array is required and must not be empty' });
    }

    // ── Build worksheet ─────────────────────────────────────────────────────
    const wb = XLSX.utils.book_new();

    // Sheet 1: Data
    const headers = Object.keys(data[0]);
    const wsData = [headers, ...data.map(row => headers.map(h => row[h] ?? ''))];
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    // Auto column widths
    ws['!cols'] = headers.map((h, colIdx) => {
      let maxLen = h.length;
      for (let r = 1; r < wsData.length; r++) {
        const v = String(wsData[r][colIdx] ?? '');
        if (v.length > maxLen) maxLen = v.length;
      }
      return { wch: Math.min(Math.max(maxLen + 2, 10), 50) };
    });

    XLSX.utils.book_append_sheet(wb, ws, 'Query Results');

    // Sheet 2: Meta  
    const metaWs = XLSX.utils.aoa_to_sheet([
      ['Generated By', 'CGMSCL GPT'],
      ['Generated At', new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })],
      ['Total Records', data.length],
      ['Query', query || 'N/A'],
    ]);
    XLSX.utils.book_append_sheet(wb, metaWs, 'Info');

    // ── Save file with unique token ────────────────────────────────────────────
    const token = crypto.randomBytes(12).toString('hex');   // 24-char unique ID
    const safeBase = (filename || 'CGMSCL_Export').replace(/[^a-zA-Z0-9_-]/g, '_');
    const outFilename = `${safeBase}_${token}.xlsx`;
    const outPath = path.join(EXPORT_DIR, outFilename);

    XLSX.writeFile(wb, outPath);

    // ── Build public URL ─────────────────────────────────────────────────────────
    // PUBLIC_BASE_URL should be set in server/.env, e.g.:
    //   PUBLIC_BASE_URL=http://your-ec2-ip:4000
    // or your domain if behind a reverse proxy.
    const baseUrl = 'http://13.235.71.165:4000';
    const fileUrl = `${baseUrl}/exports/${outFilename}`;

    // ── Auto-delete after 30 minutes ────────────────────────────────────────────────────
    const TTL_MS = 30 * 60 * 1000;   // 30 minutes
    setTimeout(() => {
      fs.unlink(outPath, (err) => {
        if (err && err.code !== 'ENOENT') console.error('[EXCEL] cleanup error:', err.message);
        else console.log(`[EXCEL] cleaned up: ${outFilename}`);
      });
    }, TTL_MS);

    console.log(`[EXCEL] Generated ${data.length} rows → ${outFilename}`);

    return res.json({
      url: fileUrl,
      filename: outFilename,
      total_records: data.length,
      expires_in: '30 minutes',
    });

  } catch (err) {
    console.error('[EXCEL] export error:', err);
    return res.status(500).json({ error: 'Excel generation failed', details: err.message });
  }
});

// ───────────────────────────────────────────────────────────────────────────
// POST /api/export-pdf   (WhatsApp only)
// Called by the WhatsApp bot after Lambda returns whatsapp_table_hint="pdf".
//
// Request body:
//   { data: Array<Object>, filename?: string, query?: string }
//
// Response:
//   { url: "http://your-server:4000/exports/abc123.pdf",
//     filename: "CGMSCL_Export_abc123.pdf",
//     total_records: N,
//     expires_in: "30 minutes" }
// ───────────────────────────────────────────────────────────────────────────
app.post('/api/export-pdf', (req, res) => {
  let PDFDocument;
  try {
    PDFDocument = require('pdfkit');
  } catch (_) {
    return res.status(500).json({ error: 'pdfkit not installed. Run: npm install pdfkit' });
  }

  try {
    const { data, filename, query } = req.body || {};

    if (!data || !Array.isArray(data) || data.length === 0) {
      return res.status(400).json({ error: 'data array is required and must not be empty' });
    }

    const token = crypto.randomBytes(12).toString('hex');
    const safeBase = (filename || 'CGMSCL_Export').replace(/[^a-zA-Z0-9_-]/g, '_');
    const outFilename = `${safeBase}_${token}.pdf`;
    const outPath = path.join(EXPORT_DIR, outFilename);

    const doc = new PDFDocument({ margin: 30, size: 'A4', layout: 'landscape' });
    const stream = fs.createWriteStream(outPath);
    doc.pipe(stream);

    const generatedAt = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

    // ── Header ──────────────────────────────────────────────────────────────
    doc.fontSize(16).font('Helvetica-Bold').text('CGMSCL Stock Report', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(9).font('Helvetica').text(`Query: ${query || 'N/A'}`, { align: 'center' });
    doc.fontSize(9).text(`Generated: ${generatedAt}  |  Total Records: ${data.length}`, { align: 'center' });
    doc.moveDown(0.8);

    // ── Table ────────────────────────────────────────────────────────────────
    const headers = Object.keys(data[0]);
    const pageWidth = doc.page.width - 60;           // 30px margin each side
    const colWidth = Math.min(pageWidth / headers.length, 130);
    const rowHeight = 14;
    let x = 30;
    let y = doc.y;

    // Header row background
    doc.rect(x, y, colWidth * headers.length, rowHeight).fill('#2c5f8a');
    doc.font('Helvetica-Bold').fontSize(8).fillColor('white');
    headers.forEach((h, i) => {
      doc.text(h.replace(/_/g, ' '), x + i * colWidth + 3, y + 3, {
        width: colWidth - 6,
        ellipsis: true,
        lineBreak: false,
      });
    });
    y += rowHeight;

    // Data rows
    doc.font('Helvetica').fontSize(8).fillColor('black');
    data.forEach((row, rowIdx) => {
      if (y + rowHeight > doc.page.height - 40) {
        doc.addPage();
        y = 30;
      }
      // Alternating row background
      if (rowIdx % 2 === 0) {
        doc.rect(x, y, colWidth * headers.length, rowHeight).fill('#f0f4f8');
        doc.fillColor('black');
      }
      headers.forEach((h, i) => {
        doc.text(String(row[h] ?? ''), x + i * colWidth + 3, y + 3, {
          width: colWidth - 6,
          ellipsis: true,
          lineBreak: false,
        });
      });
      y += rowHeight;
    });

    // ── Border around table ──────────────────────────────────────────────────
    doc.rect(x, doc.y - (data.length % (doc.page.height / rowHeight)) * rowHeight, colWidth * headers.length, 0).stroke('#cccccc');

    doc.end();

    stream.on('finish', () => {
      const baseUrl = 'http://13.235.71.165:4000';
      const fileUrl = `${baseUrl}/exports/${outFilename}`;

      // Auto-delete after 30 minutes
      setTimeout(() => {
        fs.unlink(outPath, (err) => {
          if (err && err.code !== 'ENOENT') console.error('[PDF] cleanup error:', err.message);
          else console.log(`[PDF] cleaned up: ${outFilename}`);
        });
      }, 30 * 60 * 1000);

      console.log(`[PDF] Generated ${data.length} rows → ${outFilename}`);

      return res.json({
        url: fileUrl,
        filename: outFilename,
        total_records: data.length,
        expires_in: '30 minutes',
      });
    });

    stream.on('error', (err) => {
      console.error('[PDF] stream error:', err);
      return res.status(500).json({ error: 'PDF stream failed', details: err.message });
    });

  } catch (err) {
    console.error('[PDF] export error:', err);
    return res.status(500).json({ error: 'PDF generation failed', details: err.message });
  }
});

// ───────────────────────────────────────────────────────────────────────────

app.post('/api/sessions/upsert', async (req, res) => {
  try {
    const { actor_id, session_id, title, backendType, messages } = req.body;
    if (!actor_id || !session_id) {
      return res.status(400).json({ error: 'actor_id and session_id are required' });
    }

    const updated = await ChatSession.findOneAndUpdate(
      { actor_id, session_id },
      {
        actor_id,
        session_id,
        title: title || 'New Chat',
        backendType: backendType || 'AWS',
        messages: Array.isArray(messages) ? messages : [],
        updated_at: new Date()
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    return res.json({ success: true, session: updated });
  } catch (error) {
    return res.status(500).json({ error: error.message });
  }
});

app.get('/api/sessions', async (req, res) => {
  try {
    const actorId = req.query.actor_id;
    if (!actorId) return res.status(400).json({ error: 'actor_id is required' });

    const sessions = await ChatSession.find({ actor_id: actorId })
      .sort({ updated_at: -1 })
      .lean();
    res.json({ sessions });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/api/sessions/delete', async (req, res) => {
  try {
    const { actor_id, session_id } = req.body || {};
    if (!actor_id || !session_id) {
      return res.status(400).json({ error: 'actor_id and session_id are required' });
    }
    await ChatSession.deleteOne({ actor_id, session_id });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.post('/api/feedback', async (req, res) => {
  try {
    const payload = req.body || {};
    const doc = await Feedback.create(payload);
    res.json({ success: true, feedback: doc });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

async function start() {
  const uri = process.env.MONGO_URI;
  if (!uri) {
    throw new Error('MONGO_URI is required in server/.env');
  }
  await mongoose.connect(uri);
  app.listen(PORT, () => {
    // eslint-disable-next-line no-console
    console.log(`Mongo server running on http://localhost:${PORT}`);
  });
}

start().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('Failed to start server:', err);
  process.exit(1);
});
